[General]
background=wallpaper.jpg
type=image
color=#020612
fontSize=11
font=JetBrains Mono
blur=true
blurRadius=32
jarvisIndicator=true
headerText=NewbianOS AI-Native Developer Edition
showUsersByDefault=true
